run_task1:
	g++ scan.cpp task1.cpp -Wall -O3 -std=c++17 -o task1

run_task2:
	g++ convolution.cpp task2.cpp -Wall -O3 -std=c++17 -o task2

run_task3:
	g++ task3.cpp matmul.cpp -Wall -O3 -std=c++17 -o task3

clean:
	rm FirstSlurm.out
	rm task1
	